### ISSUE TITLE
Does not compile with libssl-1.1

### ISSUE THREAD

**Issue by s3rj1k** [freeswitch/sofia-sip#2]
```
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(tport_type_ws.o): in function `tport_ws_deinit_primary':
tport_type_ws.c:(.text+0x45): undefined reference to `SSL_CTX_free'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(tport_type_ws.o): in function `tport_ws_init_primary_secure':
tport_type_ws.c:(.text+0xd4c): undefined reference to `TLS_server_method'
/usr/bin/ld: tport_type_ws.c:(.text+0xd70): undefined reference to `SSL_CTX_new'
/usr/bin/ld: tport_type_ws.c:(.text+0xd99): undefined reference to `SSL_CTX_sess_set_remove_cb'
/usr/bin/ld: tport_type_ws.c:(.text+0xdd9): undefined reference to `tls_log_errors'
/usr/bin/ld: tport_type_ws.c:(.text+0xdf9): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: tport_type_ws.c:(.text+0xe14): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: tport_type_ws.c:(.text+0xe2f): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: tport_type_ws.c:(.text+0xe4a): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: tport_type_ws.c:(.text+0xe74): undefined reference to `SSL_CTX_use_certificate_chain_file'
/usr/bin/ld: tport_type_ws.c:(.text+0xe8e): undefined reference to `tls_log_errors'
/usr/bin/ld: tport_type_ws.c:(.text+0xeb3): undefined reference to `SSL_CTX_use_certificate_file'
/usr/bin/ld: tport_type_ws.c:(.text+0xecd): undefined reference to `tls_log_errors'
/usr/bin/ld: tport_type_ws.c:(.text+0xef7): undefined reference to `SSL_CTX_use_PrivateKey_file'
/usr/bin/ld: tport_type_ws.c:(.text+0xf11): undefined reference to `tls_log_errors'
/usr/bin/ld: tport_type_ws.c:(.text+0xf2c): undefined reference to `SSL_CTX_check_private_key'
/usr/bin/ld: tport_type_ws.c:(.text+0xf46): undefined reference to `tls_log_errors'
/usr/bin/ld: tport_type_ws.c:(.text+0xf65): undefined reference to `SSL_CTX_set_cipher_list'
/usr/bin/ld: tport_type_ws.c:(.text+0xf7f): undefined reference to `tls_log_errors'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(ws.o): in function `sha1_digest':
ws.c:(.text+0x32d): undefined reference to `SHA1_Init'
/usr/bin/ld: ws.c:(.text+0x34f): undefined reference to `SHA1_Update'
/usr/bin/ld: ws.c:(.text+0x362): undefined reference to `SHA1_Final'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(ws.o): in function `ws_raw_read':
ws.c:(.text+0xd60): undefined reference to `SSL_read'
/usr/bin/ld: ws.c:(.text+0xd85): undefined reference to `SSL_get_error'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(ws.o): in function `ws_raw_write':
ws.c:(.text+0xf6e): undefined reference to `SSL_write'
/usr/bin/ld: ws.c:(.text+0x1002): undefined reference to `SSL_get_error'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(ws.o): in function `establish_logical_layer':
ws.c:(.text+0x123a): undefined reference to `SSL_new'
/usr/bin/ld: ws.c:(.text+0x1286): undefined reference to `SSL_set_fd'
/usr/bin/ld: ws.c:(.text+0x1296): undefined reference to `SSL_accept'
/usr/bin/ld: ws.c:(.text+0x12e3): undefined reference to `SSL_get_error'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.a(ws.o): in function `ws_destroy':
ws.c:(.text+0x15bf): undefined reference to `SSL_shutdown'
/usr/bin/ld: ws.c:(.text+0x15dd): undefined reference to `SSL_get_error'
/usr/bin/ld: ws.c:(.text+0x15f2): undefined reference to `SSL_free'
collect2: error: ld returned 1 exit status
```

**Comment by lordB8r** [comment]
```make[1]: Entering directory '/root/sofia-sip/utils'
        LINK sip-options
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_get_error'
....
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SHA1_Final'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:581: sip-options] Error 1
make[1]: Leaving directory '/root/sofia-sip/utils'
```
