### ISSUE TITLE
Failed to compile with gcc 14.0.1

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [freeswitch/sofia-sip#261]
here the error:
sip_basic.c: In function 'sip_identity_d':
sip_basic.c:2885:15: warning: assignment discards 'const' qualifier from pointer target ty                                                                                                                                                   pe [-Wdiscarded-qualifiers]
 2885 |           uri = pp + 1;
      |               ^
sip_basic.c:2905:40: error: passing argument 3 of 'msg_params_d' from incompatible pointer                                                                                                                                                    type [-Wincompatible-pointer-types]
 2905 |           if (msg_params_d(home, &ext, &params) >= 0) {
      |                                        ^~~~~~~
      |                                        |
      |                                        const char ***
In file included from sofia-sip/sip_parser.h:52,
                 from sip_basic.c:46:
./../msg/sofia-sip/msg_parser.h:280:55: note: expected 'const char * const**' but argument                                                                                                                                                    is of type 'const char ***'
  280 |                                   msg_param_t const **return_params);

among other non fatal warnings...

hope this helps.

**Comment by nater1983** [comment]
https://github.com/freeswitch/sofia-sip/pull/249
