### ISSUE TITLE
Openssl v3 support

### ISSUE THREAD

**Issue by IvanRibakov** [freeswitch/sofia-sip#183]
Hi, does anyone know if there are any plans or any known solutions for building sofia-sip with OpenSSL v3?

I'm trying to build FreeSWITCH for RHEL9/Rocky Linux 9, and those distros are shipped with OpenSSL v3 by default. Would like to avoid having to build OpenSSL from sources if possible...

Btw, this is the error I get when trying to build with OpenSSL 3.0.1:
```
Making all in utils
make[2]: Entering directory '/data/work/zaleos/git/softin-inivr/freeswitch/sofia-sip-1.13.9/utils'
         LINK sip-options
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_get_error'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `TLS_server_method'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_write'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_get_shutdown'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_free'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_use_certificate_chain_file'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_set_fd'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `ERR_reason_error_string'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `ERR_lib_error_string'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_read'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_new'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_use_certificate_file'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_shutdown'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `ERR_clear_error'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_sess_set_remove_cb'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_accept'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_new'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SHA1_Update'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `ERR_func_error_string'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_use_PrivateKey_file'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_cipher_list'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `tls_log_errors'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SHA1_Init'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_free'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `ERR_get_error'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SSL_CTX_check_private_key'
/usr/bin/ld: ../libsofia-sip-ua/.libs/libsofia-sip-ua.so: undefined reference to `SHA1_Final'
collect2: error: ld returned 1 exit status
```

**Comment by StefanYohansson** [comment]
I was able to compile with OpenSSL 3.0.7 without issues

```
openssl version -a
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
built on: Wed Dec 14 17:22:44 2022 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto -Wa,--noexecstack  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines-3"
MODULESDIR: "/usr/lib/ossl-modules"
Seeding source: os-specific
```

```
sofia-sip on  master [?] via C v12.2.1-gcc 
❯ ldd ./libsofia-sip-ua/.libs/libsofia-sip-ua.so.0.6.0
	linux-vdso.so.1 (0x00007ffd4c5a4000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f06a1675000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f06a15d5000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f06a1000000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f06a0e19000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f06a18a5000)
```

**Comment by StefanYohansson** [comment]
I was able to compile sofia-sip with OpenSSL v3
```
openssl version -a
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
built on: Wed Dec 14 17:22:44 2022 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto -Wa,--noexecstack  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines-3"
MODULESDIR: "/usr/lib/ossl-modules"
Seeding source: os-specific
```

```
ldd ./libsofia-sip-ua/.libs/libsofia-sip-ua.so.0.6.0
	linux-vdso.so.1 (0x00007ffd4c5a4000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f06a1675000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f06a15d5000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f06a1000000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f06a0e19000)
```

maybe this is related to FS build/make (?)

**Comment by StefanYohansson** [comment]
I have compiled sofia-sip isolated, I doubt that FS will compile with openssl 3 atm, there's a lot of code usage there that contains breaking changes. As far I can remember in rtp and other places regarding audio.

**Comment by StefanYohansson** [comment]
yeah, just as I was suspecting: https://github.com/signalwire/freeswitch/issues/1762

**Comment by themsley-voiceflex** [comment]
#1762 is closed so this one probably should be too
